<?php
namespace FlexMLS\Pages;

defined( 'ABSPATH' ) or die( 'This plugin requires WordPress' );

class Page {

	public static function custom_rewrite_rules(){
		$flexmls_settings = get_option( 'flexmls_settings' );
		$search_results_page = get_post( $flexmls_settings[ 'general' ][ 'search_results_page' ] );
		$search_results_default = !empty( $flexmls_settings[ 'general' ][ 'search_results_default' ] ) ? $flexmls_settings[ 'general' ][ 'search_results_default' ] : '';

		add_rewrite_rule( '^' . $search_results_page->post_name . '/page/([0-9]+)/?$', 'index.php?page_id=' . $search_results_page->ID . '&idxsearch=' . $search_results_default . '&idxsearch_page=$matches[1]', 'top' );
		add_rewrite_rule( '^' . $search_results_page->post_name . '/([^/]*)/page/([0-9]+)/?$', 'index.php?page_id=' . $search_results_page->ID . '&idxsearch=$matches[1]&idxsearch_page=$matches[2]', 'top' );
		add_rewrite_rule( '^' . $search_results_page->post_name . '/([^/]*)/([^/]*)/?$', 'index.php?page_id=' . $search_results_page->ID . '&idxsearch=$matches[1]&idxlisting=$matches[2]', 'top' );
		add_rewrite_rule( '^' . $search_results_page->post_name . '/([^/]*)/?$', 'index.php?page_id=' . $search_results_page->ID . '&idxsearch=$matches[1]&idxsearch_page=1', 'top' );
		add_rewrite_rule( '^' . $search_results_page->post_name . '/?$', 'index.php?page_id=' . $search_results_page->ID . '&idxsearch=' . $search_results_default . '&idxsearch_page=1', 'top' );
		add_rewrite_tag( '%idxsearch%', '([^&]+)' );
		add_rewrite_tag( '%idxlisting%', '([^&]+)' );
		add_rewrite_tag( '%idxsearch_page%', '(d+)' );
	}

	public static function maybe_update_permalink( $post_ID, $post_after, $post_before ){
		$flexmls_settings = get_option( 'flexmls_settings' );
		if( $post_ID == $flexmls_settings[ 'general' ][ 'search_results_page' ] ){
			if( $post_after->post_name != $post_before->post_name ){
				add_action( 'shutdown', '\flush_rewrite_rules' );
			}
		}
	}

	public static function search_results_page_notice( $post ){
		$flexmls_settings = get_option( 'flexmls_settings' );
		if( $post->ID == $flexmls_settings[ 'general' ][ 'search_results_page' ] ){
			echo '<div class="notice notice-warning inline"><p>You are currently editing the page that shows your Flexmls&reg; IDX search results. Content on this page will be automatically generated by the Flexmls&reg; IDX plugin. You should not delete or unpublish this page.</p></div>';
			// If the only content is the old idx_frame shortcode or if there is no content,
			// hide the WYSIWYG
			$page_content = preg_replace( '/^(\[idx_frame(?:.*)\])$/', '', $post->post_content );
			if( empty( $page_content ) ){
				remove_post_type_support( 'page', 'editor' );
			}
		}
	}

}